document.addEventListener('DOMContentLoaded',()=>{const form=document.querySelector('#search-form'),input=document.querySelector('#search-input'),results=document.querySelector('#search-results'),status=document.querySelector('#search-status');const data=[
['What Nigeria’s 2025 Tax Reform Means for SMEs','Professional Services','/insights/what-nigerias-2025-tax-reform-means-for-smes/','How changing tax rules should translate into practical planning questions for Nigerian SMEs.'],
['How to Recover Lost Revenue: A Practical Guide for Nigerian Businesses','Consulting & Advisory','/insights/recover-lost-revenue-nigerian-businesses/','Revenue leakage is rarely one problem.'],
['Diaspora Real Estate Investment: A 2025 Guide for Nigerians Abroad','Real Estate','/insights/diaspora-real-estate-investment-nigeria/','Property decisions depend on trust, verification, financing and management.'],
['Agency Banking as a Business Model: Opportunities in Nigeria’s Underbanked Market','Financial Services','/insights/agency-banking-business-model-nigeria/','Agency banking can extend financial access while creating new commercial models.'],
['How to Win Federal Government Contracts in Nigeria','Contracting','/insights/win-federal-government-contracts-nigeria/','Government contracting rewards preparation and procurement readiness.'],
['The OA Group Integrated Approach: Why One Group Can Serve the Whole Business Lifecycle','Group Insights','/insights/oa-group-integrated-approach/','Specialist capabilities can remain distinct while being coordinated around the client’s wider problem.'],
['Internal Controls vs External Audit: What Every Nigerian CEO Must Understand','Professional Services','/insights/internal-controls-vs-external-audit/','Internal controls and external audit answer different questions.'],
['Property Yield vs Capital Appreciation: Making the Right Investment Choice in Nigeria','Real Estate','/insights/property-yield-vs-capital-appreciation/','Assess recurring income and long-term value growth against investor objectives.']];
function render(q){const term=q.trim().toLowerCase();const matches=term?data.filter(x=>x.join(' ').toLowerCase().includes(term)):data;status.textContent=term?`${matches.length} result${matches.length===1?'':'s'} for “${q}”`:'Featured insights';results.innerHTML=matches.map(x=>`<article class="insight-card"><div class="insight-card__body"><div class="card-meta"><span>${x[1]}</span></div><h3>${x[0]}</h3><p class="muted">${x[3]}</p><a class="company-card__link" href="${x[2]}">Read Full Article →</a></div></article>`).join('')||'<p>No matching group insight was found. Try a broader phrase or start a conversation with OA Group.</p>'}form.addEventListener('submit',e=>{e.preventDefault();const q=input.value;history.replaceState({},'',q?'?q='+encodeURIComponent(q):location.pathname);render(q)});const q=new URLSearchParams(location.search).get('q')||'';input.value=q;render(q)});
